### ISSUE TITLE
ImportError for highspy

### ISSUE THREAD

**Issue by germannp** [ERGO-Code/HiGHS#1189]
After `> pip install highspy` I get the following problem:

```Python
> python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import highspy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\u228039\Anaconda3\lib\site-packages\highspy\__init__.py", line 30, in <module>
    from .highs import (
  File "C:\Users\u228039\Anaconda3\lib\site-packages\highspy\highs.py", line 1, in <module>
    from .highs_bindings import (
ImportError: DLL load failed while importing highs_bindings: The specified procedure could not be found.
>>>
```

Any ideas?

**Comment by jajhall** [comment]
What do you reckon @galabovaa ?

**Comment by jajhall** [comment]
Transferred to #1119
